### ISSUE TITLE
Adding a Button tag to the activity's layout.xml file 

### ISSUE THREAD

**Issue by davityle** [davityle/ngAndroid#1]
<Button
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" /> 

results in this

      Process: com.ngandroid.angularandroid, PID: 3790
           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ngandroid.angularandroid/com.ngandroid.demo.DemoActivity}: java.lang.IndexOutOfBoundsException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IndexOutOfBoundsException
            at android.content.res.StringBlock.nativeGetString(Native Method)
            at android.content.res.StringBlock.get(StringBlock.java:82)
            at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
            at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:967)
            at android.content.res.TypedArray.getValueAt(TypedArray.java:958)
            at android.content.res.TypedArray.getValue(TypedArray.java:790)
            at com.ngandroid.lib.NgAndroid.apply(NgAndroid.java:99)
            at com.ngandroid.lib.NgAndroid.setContentView(NgAndroid.java:148)
            at com.ngandroid.lib.NgAndroid.setContentView(NgAndroid.java:160)
            at com.ngandroid.demo.DemoActivity.onCreate(DemoActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by davityle** [comment]
This turned out to be a bug within the app compat v7 library -  ngAndroid will probably not be compatible with the app compat library
